#!/usr/bin/env bash
# Experiment 03 Phase 3A — canonical integrated market-data pipeline throughput
# runner.
#
# Measures ONE composed two-thread system end to end:
#
#   pre-generated byte stream
#     -> StreamDecoder -> decode_one -> MdMessage
#     -> SpscSeparatedBaselineRingBuffer<MdMessage, 4096>
#     -> MarketDataPipeline<FlatOrderBook>
#
# Every component is FROZEN: Experiment 01's book, Experiment 02's selected
# SPSC queue, and Experiment 03 Phases 1A / 1B / 2. Nothing was modified to move
# a number, and nothing here may be reported as if it were.
#
# ---------------------------------------------------------------------------
# WHAT THE REPORTED NUMBER IS
# ---------------------------------------------------------------------------
# messages_per_second = live messages consumed / elapsed_ns, where elapsed is
#
#   [release start gate]  ->  [the consumer's final apply]
#
# taken by the consumer thread itself. It INCLUDES stream framing, binary
# decode, message construction, the queue handoff, the producer's queue-full
# retry loop, the consumer's queue-empty retry loop, sequence validation,
# snapshot/staging bookkeeping and the FlatOrderBook apply.
#
# It is NOT a latency, NOT a percentile and NOT a per-message cost. Phase 3A
# measures throughput only: there is no clock read per message, MdMessage
# carries no timestamp and no side timestamp array exists. Per-message
# measurement is Phase 3B and is deliberately not started here.
#
# It is also NOT exchange throughput, NOT production trading throughput and NOT
# wire-to-exchange anything. It is one synthetic workload on one host under one
# chunk policy and one queue capacity, comparable only to another run of THIS
# tool with the same workload on the same host.
#
# ---------------------------------------------------------------------------
# ONE CANONICAL CELL — there is no matrix here, and that is deliberate
# ---------------------------------------------------------------------------
# Phase 3A establishes a BASELINE. The chunk size (64 KiB) and the queue
# capacity (4096) are compile-time constants in the benchmark and are not
# options; the argument parser refuses unrecognised flags precisely so that a
# treatment matrix cannot appear by accident. Phase 3A does NOT compare:
#
#   cached vs baseline SPSC      (Experiment 02 Phase 3B, already frozen)
#   SameLine vs Separated        (Experiment 02 Phase 3A, already frozen)
#   Flat vs Map order book       (Experiment 01, already frozen)
#   multiple queue capacities    (separate phase)
#   multiple chunk sizes         (separate phase)
#
# Those are separate experiments with separate result directories. In
# particular the Phase-2 SPSC numbers are NOT comparable to these: a Phase-2
# message is a raw payload on an empty queue, whereas a Phase-3A message is
# framed, decoded, sequenced and APPLIED to a live order book.
#
# ---------------------------------------------------------------------------
# THE SESSION DESIGN
# ---------------------------------------------------------------------------
# FOUR sessions, five measured repetitions each, plus one excluded warm-up per
# process. One process per session: no two sessions share an address space or a
# warmed-up cache state.
#
# There is only ONE cell, so there is no cell ordering to balance — an AB/BA
# counterbalance needs two treatments and this phase has one. What the four
# sessions DO give is a direct read on temporal drift: with the cell held
# fixed, all variation between session medians is temporal, and the dataset
# reports it rather than hiding it inside a single number.
#
# The four sessions are run back-to-back and are therefore NOT independent of
# each other. They are not four independent trials of a randomised experiment.
#
# The published figure is: per-session median of the 5 measured repetitions,
# then the median across the 4 session medians. Every raw repetition is
# preserved; nothing is pooled into a single giant observation.
#
# Usage:
#   scripts/market-data-throughput.sh              # full canonical run
#   FORCE=1 scripts/market-data-throughput.sh      # overwrite an existing dataset
#   SMOKE=1 scripts/market-data-throughput.sh      # tiny run, non-canonical, into OUT
set -euo pipefail

cd "$(dirname "$0")/.."

BIN_NAME="market_data_pipeline_throughput_bench"
FORCE="${FORCE:-0}"
BUILDDIR="${BUILDDIR:-build-market-data-throughput}"
ARCH_FLAGS="${BENCH_ARCH_FLAGS:-}"
SMOKE="${SMOKE:-0}"

# The defaults are chosen from the mode FIRST. Setting them in one place and
# then trying to override them in the smoke branch does not work: `X="${X:-d}"`
# leaves X non-empty, so a later `X="${X:-smoke}"` is dead code — which is how a
# smoke run once wrote into a CANONICAL output directory elsewhere in this repo.
# One branch, one set of defaults, no override that cannot fire.
if [[ "$SMOKE" == "1" ]]; then
    # Non-canonical: same shape and the same output LAYOUT, tiny counts, so the
    # whole pipeline including the analyzer can be exercised before the real
    # run. It writes to its own directory and never to the canonical one.
    MESSAGES="${MESSAGES:-200000}"
    REPS="${REPS:-3}"
    WARMUP="${WARMUP:-1}"
    OUT="${OUT:-$BUILDDIR/smoke-market-data-throughput}"
else
    MESSAGES="${MESSAGES:-5000000}"
    REPS="${REPS:-5}"
    WARMUP="${WARMUP:-1}"
    OUT="${OUT:-docs/results/market-data-throughput}"
fi

BENCH_REL="$BUILDDIR/$BIN_NAME"

SESSIONS=4
EXPECTED_PROCESSES=$SESSIONS
EXPECTED_MEASURED_REPETITIONS=$(( EXPECTED_PROCESSES * REPS ))

if [[ "$REPS" -lt 1 ]]; then echo "FATAL: REPS must be >= 1 (got $REPS)" >&2; exit 1; fi
if [[ "$WARMUP" -lt 0 ]]; then echo "FATAL: WARMUP must be >= 0 (got $WARMUP)" >&2; exit 1; fi
if [[ "$MESSAGES" -lt 1000 ]]; then
    echo "FATAL: MESSAGES must be >= 1000 (got $MESSAGES)" >&2; exit 1
fi

# ---------------------------------------------------------------------------
# Host load pre-flight
# ---------------------------------------------------------------------------
# This is a throughput measurement on two unpinned spinning threads. If the
# machine is saturated, the figure reflects the host's scheduler rather than the
# pipeline: the consumer's retry loop is a spin, so a descheduled consumer
# starves the queue and the producer stalls behind it.
#
# BE CLEAR ABOUT WHAT THIS CHECK IS AND IS NOT. The default is the LOGICAL CPU
# COUNT, so it fires only when the host is saturated — it deliberately permits
# ordinary desktop background activity, because that is the ambient condition
# this repo's other frozen benchmark datasets were measured under, and a
# threshold that forbade it would make this runner unusable on the machine it
# was written for.
#
# It is a coarse PRE-FLIGHT, not the authoritative guard. It cannot see load
# that arrives after it is read. The authoritative guard runs at the end, over
# every repetition, in scripts/analyze-market-data-throughput.py, which refuses
# the dataset if any repetition ran far slower than its own session's median.
# Set MAX_LOADAVG=0 to disable the pre-flight; there is no switch for the other.
MAX_LOADAVG="${MAX_LOADAVG:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 8)}"

read_loadavg_1min() {
    # macOS: sysctl prints "{ 1.23 4.56 7.89 }". Linux: /proc/loadavg.
    if [[ -r /proc/loadavg ]]; then
        cut -d' ' -f1 /proc/loadavg
    elif command -v sysctl >/dev/null 2>&1; then
        sysctl -n vm.loadavg 2>/dev/null | tr -d '{}' | awk '{print $1}'
    else
        echo "unknown"
    fi
}

LOADAVG_START="$(read_loadavg_1min)"
UPTIME_START="$(uptime | sed 's/.*load averages: //')"

if [[ "$MAX_LOADAVG" != "0" ]]; then
    if [[ "$LOADAVG_START" == "unknown" ]]; then
        echo "WARNING: cannot read the 1-minute load average on this host; the" >&2
        echo "         pre-flight load check is being SKIPPED. Verify the host was" >&2
        echo "         otherwise idle before citing this dataset." >&2
    elif awk -v l="$LOADAVG_START" -v m="$MAX_LOADAVG" 'BEGIN{exit !(l > m)}'; then
        cat >&2 <<EOF
FATAL: 1-minute load average is $LOADAVG_START but MAX_LOADAVG=$MAX_LOADAVG.

Refusing to run. This is a throughput measurement on two unpinned spinning
threads; on a saturated host the figure reflects the host's scheduler, not the
integrated pipeline. Wait for the machine to quiesce — including build jobs,
test runs and anything else you started — then re-run.

Note that the load average is only a pre-flight. It cannot see load that
arrives AFTER it is read. The authoritative check runs at the end, over every
repetition, in scripts/analyze-market-data-throughput.py.

To override anyway: MAX_LOADAVG=0 $0
Any dataset produced under that override must be labelled as load-uncontrolled,
because the load average is then unrecorded and unenforced.
EOF
        exit 1
    fi
fi

# ---------------------------------------------------------------------------
# Guard against clobbering an existing dataset
# ---------------------------------------------------------------------------
if [[ -e "$OUT" && "$FORCE" != "1" && "$SMOKE" != "1" ]]; then
    echo "FATAL: $OUT already exists. Re-run with FORCE=1 to overwrite." >&2
    exit 1
fi
# Always start from an empty tree: a leftover file from an earlier run would be
# picked up by the analyzer as a live result.
rm -rf "$OUT"
mkdir -p "$OUT/raw" "$OUT/summaries" "$OUT/stderr"

# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------
echo "==> Configuring and building $BIN_NAME (Release, forced -O3 -DNDEBUG)"
cmake -S . -B "$BUILDDIR" -DCMAKE_BUILD_TYPE=Release -DBENCH_ARCH_FLAGS="$ARCH_FLAGS" >/dev/null
cmake --build "$BUILDDIR" --target "$BIN_NAME" -j >/dev/null

BENCH="$BENCH_REL"
if [[ ! -x "$BENCH" ]]; then echo "FATAL: $BENCH is not executable" >&2; exit 1; fi

echo
echo "==> Experiment 03 Phase 3A — integrated market-data pipeline throughput"
echo "    output            : $OUT"
echo "    load avg (1 min)  : $LOADAVG_START (pre-flight limit $MAX_LOADAVG; 0 = disabled)"
echo "    chunk policy      : 64 KiB (compile-time constant, not an option)"
echo "    queue capacity    : 4096 (compile-time constant, not an option)"
echo "    live messages     : $MESSAGES per process (plus a 130-message snapshot)"
echo "    sessions          : $SESSIONS (sequential; NOT independent trials)"
echo "    measured reps     : $REPS per session (+$WARMUP excluded warm-up)"
if [[ "$SMOKE" == "1" ]]; then
    echo "    *** SMOKE MODE — NON-CANONICAL, MUST NOT BE CITED ***"
fi
echo

# ---------------------------------------------------------------------------
# command.txt — every effective invocation, in the order it ran
# ---------------------------------------------------------------------------
{
    echo "# Experiment 03 Phase 3A — integrated market-data pipeline throughput:"
    echo "# exact invocations, in the order they ran."
    echo "#"
    echo "# repo HEAD: $(git rev-parse HEAD 2>/dev/null || echo 'not a git repository')"
    echo "# binary: $BENCH_REL"
    echo "# messages=$MESSAGES reps=$REPS warmup=$WARMUP sessions=$SESSIONS"
    echo "# chunk_bytes=65536 queue_capacity=4096 (compile-time constants)"
    echo "#"
    echo "# THE MEASURED QUANTITY is [release start gate] -> [the consumer's final"
    echo "# apply], stamped by the consumer thread itself. It INCLUDES stream"
    echo "# framing, binary decode, the queue handoff, BOTH retry loops, sequence"
    echo "# validation, staging bookkeeping and the FlatOrderBook apply. It is NOT"
    echo "# a latency, NOT a percentile and NOT a per-message cost."
    echo "#"
    echo "# THE TIMED REGION CONTAINS NO SNAPSHOT. A small valid snapshot is applied"
    echo "# BEFORE the gate: the producer feeds only the snapshot bytes and parks,"
    echo "# the consumer drains exactly the snapshot's 130 messages and parks, and"
    echo "# the clock starts only after both are parked. So the window carries no"
    echo "# recovery, no malformed bytes, no sequence gap, no stale message, no"
    echo "# terminal decode error and no truncated input."
    echo "#"
    echo "# THE COMPONENTS ARE FROZEN. None was modified to move a number. The"
    echo "# frozen ThreadedMdPipeline is run over the SAME bytes before timing and"
    echo "# must agree with a single-threaded reference on every observable and all"
    echo "# twenty counters, which is what licenses this harness's own thread pair."
    echo "#"
    echo "# CHUNK SIZE AND CAPACITY ARE NOT OPTIONS. The parser refuses unknown"
    echo "# flags, so no treatment matrix can be produced by accident. Phase 3A"
    echo "# does NOT compare queue variants, books, capacities or chunk sizes."
    echo "#"
    echo "# THE FOUR SESSIONS ARE SEQUENTIAL AND NOT INDEPENDENT. They are not four"
    echo "# randomised trials; with one fixed cell they are a read on temporal"
    echo "# drift, and the session spread is reported rather than averaged away."
} >"$OUT/command.txt"

# ---------------------------------------------------------------------------
# The canonical run
# ---------------------------------------------------------------------------
for session in $(seq 1 "$SESSIONS"); do
    {
        echo
        echo "# ---- session $session/$SESSIONS ----"
    } >>"$OUT/command.txt"

    echo "==> Session $session/$SESSIONS"

    raw="$OUT/raw/session${session}.csv"
    summary="$OUT/summaries/session${session}.txt"
    stderr_log="$OUT/stderr/session${session}.txt"

    # The invocation is built as an array and serialized with %q quoting
    # (bash 3.2 has no ${arr[@]@Q}), so command.txt records exactly what ran,
    # in the order it ran.
    cmd=("$BENCH_REL" "--messages=$MESSAGES" "--reps=$REPS" "--warmup=$WARMUP"
         "--raw-out=$raw" "--summary-out=$summary")
    for a in "${cmd[@]}"; do printf '%q ' "$a"; done >>"$OUT/command.txt"
    printf '\n' >>"$OUT/command.txt"

    # A failing session aborts the run: set -e propagates the benchmark's
    # non-zero exit, and nothing downstream publishes the session.
    #
    #   exit 2  a malformed or off-cell invocation was refused
    #   exit 3  the pre-timing reference disagreed (generator/encoder defect)
    #   exit 4  a repetition failed its own invariants, or the checksum did not
    #           match the reference — the cell is NOT publishable
    "$BENCH" --messages="$MESSAGES" --reps="$REPS" --warmup="$WARMUP" \
             --raw-out="$raw" --summary-out="$summary" \
             >/dev/null 2>"$stderr_log"
done

LOADAVG_END="$(read_loadavg_1min)"

echo
echo "==> All $EXPECTED_PROCESSES sessions completed and validated"
echo "    load avg (1 min) at end: $LOADAVG_END"

# ---------------------------------------------------------------------------
# run_order.txt — the execution order parsed back OUT of command.txt, so the
# record and the order cannot disagree.
# ---------------------------------------------------------------------------
grep -F "${BIN_NAME} " "$OUT/command.txt" 2>/dev/null \
    | sed 's/^[^ ]* //' > "$OUT/run_order.txt" || true

# ---------------------------------------------------------------------------
# SESSIONS.md — the session design, stated plainly
# ---------------------------------------------------------------------------
{
    echo "# Experiment 03 Phase 3A — session design"
    echo
    echo "| session | cell | processes | measured reps | warm-up |"
    echo "|---|---|---|---|---|"
    for session in $(seq 1 "$SESSIONS"); do
        echo "| $session | 64 KiB chunks / capacity 4096 | 1 | $REPS | $WARMUP |"
    done
    echo
    echo "One process per session, and one cell in the whole phase, so every"
    echo "session measures the **same** configuration at a different point in time."
    echo
    echo "**What the four sessions buy:** with the cell held fixed, all variation"
    echo "between session medians is temporal. The dataset reports that spread"
    echo "instead of folding it into a single number with no error bar."
    echo
    echo "**What they do NOT buy:** they are run back-to-back and are therefore NOT"
    echo "independent trials, and this is not a randomised experiment. There is no"
    echo "AB/BA counterbalance here because there is no treatment pair — Phase 3A"
    echo "has one cell and compares nothing. No claim of a controlled thermal or"
    echo "frequency regime is made anywhere in this dataset."
    echo
    echo "**Published figure:** the per-session median of the $REPS measured"
    echo "repetitions, then the median across the $SESSIONS session medians. Every"
    echo "raw repetition is preserved in \`raw/\`. No repetition is discarded and"
    echo "repetitions are never pooled into one giant observation."
} >"$OUT/SESSIONS.md"

# ---------------------------------------------------------------------------
# HOST.md — host and toolchain metadata
# ---------------------------------------------------------------------------
{
    echo "# Experiment 03 Phase 3A — host and toolchain metadata"
    echo
    echo "Measured with \`$BIN_NAME\` built from repo HEAD"
    echo "\`$(git rev-parse HEAD 2>/dev/null || echo 'not a git repository')\`."
    echo
    echo "| property | value |"
    echo "|---|---|"
    echo "| hostname | \`$(hostname)\` |"
    echo "| uname | \`$(uname -a)\` |"
    echo "| macOS | \`$(sw_vers -productVersion 2>/dev/null || echo unknown)\` |"
    echo "| CPU | \`$(sysctl -n machdep.cpu.brand_string 2>/dev/null || echo unknown)\` |"
    echo "| logical CPUs | $(sysctl -n hw.ncpu 2>/dev/null || echo unknown) |"
    echo "| performance cores | $(sysctl -n hw.perflevel0.physicalcpu 2>/dev/null || echo unknown) |"
    echo "| efficiency cores | $(sysctl -n hw.perflevel1.physicalcpu 2>/dev/null || echo unknown) |"
    echo "| reported cache line | $(sysctl -n hw.cachelinesize 2>/dev/null || echo unknown) bytes |"
    echo "| compiler | \`$(/usr/bin/c++ --version 2>/dev/null | head -2 | tr '\n' ' ')\` |"
    echo "| build type | Release, forced \`-O3 -DNDEBUG\` |"
    echo "| extra arch flags | \`${ARCH_FLAGS}\` (empty = compiler default) |"
    echo "| clock | \`std::chrono::steady_clock\` only, read twice per repetition |"
    echo "| load average (1 min) at start | \`$LOADAVG_START\` |"
    echo "| load average (1 min) at end | \`$LOADAVG_END\` |"
    echo "| pre-flight load limit | \`$MAX_LOADAVG\` (0 = check disabled) |"
    echo "| uptime at start | \`$UPTIME_START\` |"
    echo
    echo "Thread placement is NOT controlled: no affinity, no pinning and no thread"
    echo "priority is set anywhere in this experiment. macOS may migrate either"
    echo "thread mid-run, and the two threads may land on different core types. No"
    echo "measurement in this dataset observes which cores were used, so no result"
    echo "here may be attributed to a core type."
    echo
    echo "The reported figure is therefore **host-specific**, and the host was NOT"
    echo "quiesced beyond the load-average pre-flight. It must not be quoted as a"
    echo "property of the pipeline alone."
    echo
    echo "## Exact sources that produced this dataset"
    echo
    echo "A commit hash alone does not describe a working tree with uncommitted"
    echo "changes, so the digest of each source file is recorded here. The digest is"
    echo "of the file ON DISK at run time, which is what the binary was built from."
    echo
    echo '```'
    echo "git HEAD: $(git rev-parse HEAD 2>/dev/null || echo 'not a git repository')"
    echo
    echo "working tree at run time (git status --short):"
    git status --short 2>/dev/null || echo "  (not a git repository)"
    echo
    for f in benchmark/market_data_pipeline_throughput_bench.cpp \
             scripts/market-data-throughput.sh \
             scripts/analyze-market-data-throughput.py \
             market-data-pipeline/include/md_stream_decoder.h \
             market-data-pipeline/include/md_threaded_pipeline.h \
             market-data-pipeline/include/market_data_pipeline.h \
             market-data-pipeline/include/md_decoder.h \
             market-data-pipeline/include/md_encoder.h \
             market-data-pipeline/include/md_stream_gen.h \
             include/spsc_remote_cursor_ring_buffer.h \
             include/flat_order_book.h \
             include/types.h; do
        if [[ -f "$f" ]]; then
            printf 'sha256  %s  %s\n' "$(shasum -a 256 "$f" | cut -d' ' -f1)" "$f"
        else
            printf 'sha256  %s  %s\n' "MISSING" "$f"
        fi
    done
    echo '```'
} >"$OUT/HOST.md"

# ---------------------------------------------------------------------------
# Verify and derive. The analyzer refuses to emit a table unless every session
# passes, so a dataset and its derived tables are never produced by different
# steps and can never drift apart.
# ---------------------------------------------------------------------------
echo
echo "==> Verifying every session and deriving the cross-session tables"
if command -v python3 >/dev/null 2>&1; then
    python3 scripts/analyze-market-data-throughput.py "$OUT" 2>&1 \
        | tee "$OUT/invariants.txt"
    VERIFY_RC="${PIPESTATUS[0]}"
    if [[ "$VERIFY_RC" != "0" ]]; then
        echo "FATAL: verification FAILED (exit $VERIFY_RC)." >&2
        echo "       The dataset is NOT verified and must not be cited." >&2
        exit 1
    fi
else
    echo "FATAL: python3 not found; the verification could not run." >&2
    echo "       The dataset is NOT verified and must not be cited." >&2
    exit 1
fi

echo
echo "==> Phase 3A dataset complete: $OUT"
echo "    sessions                 : $EXPECTED_PROCESSES"
echo "    measured repetitions      : $EXPECTED_MEASURED_REPETITIONS"
echo "    live messages per session: $MESSAGES"
if [[ "$SMOKE" == "1" ]]; then
    echo "    *** NON-CANONICAL SMOKE RUN — MUST NOT BE CITED ***"
fi
echo "    verification record      : $OUT/invariants.txt"
echo "    summary                  : $OUT/SUMMARY.csv"
