#!/usr/bin/env bash
# Phase 3M (macOS / Apple Silicon) Instruments automation via xctrace.
#
# xctrace is the CLI for Instruments and ships only with a FULL Xcode install.
# If xctrace is not on PATH (e.g. this host has Command Line Tools only), the
# script stops with a clear instruction: install / point at full Xcode. It never
# guesses at template names or invents xctrace arguments it cannot verify.
#
# One real invocation records ONE cell as:
#   one process  /  one benchmark cell  /  one measured apply block  /
#   one signpost interval   (reps is FORCED to 1 — see below)
# into a transient result dir under results/ (git-ignored). Nothing is
# auto-committed; after inspection the user moves summaries into
# docs/results/phase3-macos-apple-silicon/.
#
# Usage:
#   scripts/phase3m-instruments.sh [--template=NAME] <impl> <workload> <scale> \
#       [updates=N] [reps=N] [--signposts] [--dry-run]
#     --template=NAME  Instruments template (default: 'Time Profiler'). The name
#                      must match EXACTLY (case-insensitive) one listed by
#                      `xctrace list templates`; partial names are rejected.
#     impl         map | flat
#     workload     A | B | C | D | E
#     scale        1000 | 10000 | 100000 | 1000000
#     updates=N    steady ops per timed block     (default 2000000)
#     reps=N       must be 1 for profiling — REJECTED otherwise (exit 2).
#                  One recording = one measured apply block. (The Phase 2
#                  benchmark itself still supports reps=3; only this wrapper
#                  enforces reps=1.)
#     --signposts  pass LLOB_SIGNPOSTS=1 to the benchmark so the
#                  'llob.apply.block' interval appears in the recording. Passed
#                  through xctrace's --env when supported (so it reaches the
#                  benchmark, not just xctrace); otherwise exported to the
#                  inherited environment.
#     --dry-run    print the exact commands without recording (default off).
#
# Template detection is EXACT: `xctrace list templates` output is normalized
# (per-line template names) and the requested name must match one of them
# exactly; a partial name like 'Time' is rejected even though 'Time Profiler'
# exists. On failure the script prints the requested name and the full list.
#
# xctrace writes an opaque .trace bundle; the benchmark's stdout is captured
# into the same result dir via xctrace's target-stdout handling when supported
# (the process output is recorded into the .trace), and also echoed to
# bench_stdout.txt. host.txt is generated by
# scripts/collect-macos-profile-metadata.sh.

set -euo pipefail

cd "$(dirname "$0")/.."          # project root

# ---- defaults ---------------------------------------------------------------
TEMPLATE="Time Profiler"
SIGNPOSTS=0
DRYRUN=0
IMPL=""; WORKLOAD=""; SCALE=""
UPDATES=2000000
REPS=1

for a in "$@"; do
    case "$a" in
        --template=*)  TEMPLATE="${a#--template=}" ;;
        updates=*)     UPDATES="${a#updates=}" ;;
        reps=*)        REPS="${a#reps=}" ;;
        --signposts)   SIGNPOSTS=1 ;;
        --dry-run)     DRYRUN=1 ;;
        -h|--help)
            sed -n '1,55p' "$0" | grep -E '^#( |$)' | sed 's/^# \{0,1\}//'
            exit 0 ;;
        --template)    echo "use --template=NAME (with '=')" >&2; exit 2 ;;
        *)  # positional impl workload scale
            if [[ -z "$IMPL" ]]; then IMPL="$a";
            elif [[ -z "$WORKLOAD" ]]; then WORKLOAD="$a";
            elif [[ -z "$SCALE" ]]; then SCALE="$a";
            else echo "unexpected argument: $a" >&2; exit 2; fi ;;
    esac
done

# ---- basic arg validation ----------------------------------------------------
if [[ -z "$IMPL" || -z "$WORKLOAD" || -z "$SCALE" ]]; then
    echo "usage: scripts/phase3m-instruments.sh [--template=NAME] <impl> <workload> <scale> [updates=N] [reps=N] [--signposts] [--dry-run]" >&2
    exit 2
fi
case "$IMPL" in map|flat) ;; *) echo "impl must be map|flat" >&2; exit 2 ;; esac
case "$WORKLOAD" in A|B|C|D|E) ;; *) echo "workload must be A|B|C|D|E" >&2; exit 2 ;; esac

# ---- item 1: enforce reps=1 (Phase 3M) ---------------------------------------
if [[ "$REPS" != "1" ]]; then
    echo "error: Phase 3M profiling requires reps=1 (got reps=${REPS})." >&2
    echo "  One Instruments recording = one process / one cell / one measured" >&2
    echo "  apply block / one signpost interval. best-of-N (Phase 2 reps=3) has" >&2
    echo "  no single interval to pair with a recording. The Phase 2 benchmark" >&2
    echo "  still supports reps>1; only this profiling wrapper enforces reps=1." >&2
    exit 2
fi

# ---- gate: xctrace requires full Xcode --------------------------------------
# Capability is detected at RECORDING time (this is not a permanent host claim —
# the same repo on an Xcode Mac will simply proceed). See docs/profiling/.
if ! command -v xcrun >/dev/null 2>&1 || ! xcrun --find xctrace >/dev/null 2>&1; then
    echo "error: xctrace is not available here (xcrun --find xctrace failed)." >&2
    echo "  xctrace ships with FULL Xcode (Instruments). If you installed Xcode," >&2
    echo "  run:  sudo xcode-select -s /Applications/Xcode.app" >&2
    echo "  Otherwise install Xcode from the Mac App Store, then re-run." >&2
    echo "  The tooling is ready; a real trace belongs under" >&2
    echo "  docs/results/phase3-macos-apple-silicon/ after inspection." >&2
    exit 3
fi

# ---- detect the requested template EXACTLY (never a substring) ---------------
# Normalize `xctrace list templates` output to one candidate name per line, then
# require an exact (case-insensitive) match. A partial name must NOT pass merely
# because it is a prefix of a real template.
avail="$(xcrun xctrace list templates 2>/dev/null || true)"
norm="$(printf '%s\n' "$avail" | sed -E 's/[[:space:]]*$//')"
if ! grep -Fxiq -- "$TEMPLATE" <<<"$norm"; then
    echo "error: Instruments template '$TEMPLATE' not found (exact match required)." >&2
    echo "  Requested: $TEMPLATE" >&2
    echo "  Available templates on this host:" >&2
    echo "$norm" | sed 's/^/    /' >&2
    echo "  Pass the exact name, e.g. --template='Time Profiler'." >&2
    exit 3
fi

# ---- detect xctrace record --env support (item 5) -----------------------------
# Prefer passing LLOB_SIGNPOSTS=1 through xctrace's launch-environment mechanism
# so the variable reaches orderbook_bench (not just xctrace). Not every xctrace
# supports --env the same way, so probe the local tool and fall back to an
# inherited export rather than inventing arguments.
XCTRACE_ENV=()
if [[ "$SIGNPOSTS" -eq 1 ]]; then
    if xcrun xctrace record --help 2>&1 | grep -q -- '--env'; then
        XCTRACE_ENV=(--env LLOB_SIGNPOSTS=1)
        SIGNPOST_MEANS="xctrace --env"
    else
        SIGNPOST_MEANS="inherited env"
    fi
fi

# ---- build (fresh dir, Release, no stale arch flags) -------------------------
if [[ "$DRYRUN" -eq 1 ]]; then
    echo "==> DRY-RUN: no build, no recording. Exact commands:"
    echo "  rm -rf build-perf && cmake -S . -B build-perf -DCMAKE_BUILD_TYPE=Release -DBENCH_ARCH_FLAGS= && cmake --build build-perf"
else
    echo "==> Configuring (Release, fresh build-perf dir)"
    rm -rf build-perf
    cmake -S . -B build-perf -DCMAKE_BUILD_TYPE=Release -DBENCH_ARCH_FLAGS= >/dev/null
    cmake --build build-perf >/dev/null
fi

BIN=./build-perf/orderbook_bench

# ---- transient result dir (item 6) -------------------------------------------
# One reproducible result directory per invocation. Transient (results/ is
# git-ignored); NOT auto-committed. The user moves inspected summaries into
# docs/results/phase3-macos-apple-silicon/ afterwards.
TS="$(date +%Y%m%d-%H%M%S)"
RDIR="results/phase3m_${IMPL}_${WORKLOAD}_${SCALE}_${TS}"
OUT="$RDIR/recording.trace"
SB="$RDIR/bench_stdout.txt"
CMD="$RDIR/command.txt"
HOST="$RDIR/host.txt"

# A dry run prints paths but creates nothing — the dir is only made for a real
# recording, so an inspect-only invocation leaves no empty results/ litter.
if [[ "$DRYRUN" -eq 0 ]]; then
    mkdir -p results "$RDIR"
    # host.txt: real machine/tool availability lives here (recording time), not
    # in static docs (item 7).
    scripts/collect-macos-profile-metadata.sh "$HOST" >/dev/null
    echo "  host metadata -> $HOST"
fi

# ---- assemble the exact effective command (item 6: command.txt) --------------
LAUNCH_ARGS=(-- "$BIN" "$IMPL" "$WORKLOAD" "$SCALE" "updates=$UPDATES" "reps=$REPS")
if [[ "$SIGNPOSTS" -eq 1 ]]; then
    ENVLN="LLOB_SIGNPOSTS=1 via ${SIGNPOST_MEANS}"
else
    ENVLN="(unset — no signpost interval)"
fi

if [[ "$DRYRUN" -eq 1 ]]; then
    echo "==> DRY-RUN: no build, no recording. Exact commands:"
    echo "  rm -rf build-perf && cmake -S . -B build-perf -DCMAKE_BUILD_TYPE=Release -DBENCH_ARCH_FLAGS= && cmake --build build-perf"
    echo "  xcrun xctrace record --template '$TEMPLATE' --output '$OUT' ${XCTRACE_ENV[@]+"${XCTRACE_ENV[@]}"} --launch ${LAUNCH_ARGS[@]+"${LAUNCH_ARGS[@]}"}"
    echo "  result dir: $RDIR/   (bench_stdout.txt, host.txt, command.txt)"
    echo "  env: $ENVLN"
    echo "Run without --dry-run to actually record (full Xcode required)."
    exit 0
fi

# ---- write command.txt BEFORE running (exact effective configuration) --------
{
    echo "# Phase 3M recording command — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
    echo "cell:       $IMPL $WORKLOAD $SCALE"
    echo "updates:    $UPDATES"
    echo "reps:       1 (enforced)"
    echo "template:   $TEMPLATE"
    echo "signposts:  $ENVLN"
    echo "command:"
    echo "  xcrun xctrace record --template '$TEMPLATE' --output '$OUT' ${XCTRACE_ENV[@]+"${XCTRACE_ENV[@]}"} --launch ${LAUNCH_ARGS[@]+"${LAUNCH_ARGS[@]}"}"
} > "$CMD"

echo "==> recording: template='$TEMPLATE'  cell=$IMPL $WORKLOAD $SCALE  updates=$UPDATES reps=1  signposts=$ENVLN"
echo "    result dir: $RDIR/"

# ---- run xctrace --------------------------------------------------------------
# Export LLOB_SIGNPOSTS into the environment too (belt-and-suspenders): if --env
# is unsupported the inherited env still reaches the benchmark; if --env IS used,
# the explicit --env is the authoritative copy.
if [[ "$SIGNPOSTS" -eq 1 ]]; then export LLOB_SIGNPOSTS=1; else unset LLOB_SIGNPOSTS 2>/dev/null || true; fi

# xctrace --launch runs the target as a child and forwards its stdout to
# xctrace's own stdout on most builds. We capture that combined output to
# bench_stdout.txt so the benchmark's real data row is preserved as text when the
# local xctrace forwards it. If the local xctrace does NOT forward target stdout
# (the row is only inside the .trace), bench_stdout.txt gets an explicit note
# instead of a fabricated number. The .trace always contains the target output.
set +e
xcrun xctrace record \
    --template "$TEMPLATE" \
    --output "$OUT" \
    ${XCTRACE_ENV[@]+"${XCTRACE_ENV[@]}"} \
    --launch "${LAUNCH_ARGS[@]}" >"$SB" 2>&1
XRC=$?
set -e
if [[ "$XRC" -ne 0 ]]; then
    echo "error: xctrace record failed (exit $XRC). See $SB" >&2
    exit "$XRC"
fi

# If the data row is present in the captured stdout, keep it; otherwise note that
# the row lives only inside the .trace and must be captured from there or from a
# same-cell normal run. Never fabricate a number.
if ! grep -qE '^(map|flat),' "$SB"; then
    printf '\n# bench_stdout: the data row is inside %s (this xctrace did not\n' "$OUT" >> "$SB"
    printf '# forward target stdout as text). Capture it from the .trace, or run the\n' >> "$SB"
    printf '# same cell once ungated for the ns/update anchor. No number is fabricated.\n' >> "$SB"
fi

echo "==> recorded: $OUT"
echo "    result dir: $RDIR/"
echo "      recording.trace   the Instruments trace (open with: open '$OUT')"
echo "      bench_stdout.txt  benchmark stdout / data row (see note inside if not a number)"
echo "      host.txt          machine/tool metadata (recording-time)"
echo "      command.txt       exact effective command"
echo "    Open in Instruments, select the 'llob.apply.block' signpost interval to scope"
echo "    to the timed apply() block. After inspection, move summaries into"
echo "    docs/results/phase3-macos-apple-silicon/. Results are NOT auto-committed."
